<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<hr>
	<div align="center">
		<div>
			<h1>자유게시판</h1>
		</div>
		<div>
			<table class="table">
				<thead class="table-dark">
					<tr>
						<th>글번호</th>
						<th>제목</th>
						<th>내용</th>
						<th>작성일</th>
						<th>조회수</th>
						<th>추천수</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>0</td>
						<td>제목제목제목제목제목</td>
						<td>내용내용내용내용내용내용내용</td>
						<td>2022-09-22</td>
						<td>0</td>
						<td>0</td>
					</tr>
					<tr>
						<td>0</td>
						<td>제목제목제목제목제목</td>
						<td>내용내용내용내용내용내용내용</td>
						<td>2022-09-22</td>
						<td>0</td>
						<td>0</td>
					</tr>
					<tr>
						<td>0</td>
						<td>제목제목제목제목제목</td>
						<td>내용내용내용내용내용내용내용</td>
						<td>2022-09-22</td>
						<td>0</td>
						<td>0</td>
					</tr>
					<tr>
						<td>0</td>
						<td>제목제목제목제목제목</td>
						<td>내용내용내용내용내용내용내용</td>
						<td>2022-09-22</td>
						<td>0</td>
						<td>0</td>
					</tr>
					<tr>
						<td>0</td>
						<td>제목제목제목제목제목</td>
						<td>내용내용내용내용내용내용내용</td>
						<td>2022-09-22</td>
						<td>0</td>
						<td>0</td>
					</tr>
					<tr>
						<td>0</td>
						<td>제목제목제목제목제목</td>
						<td>내용내용내용내용내용내용내용</td>
						<td>2022-09-22</td>
						<td>0</td>
						<td>0</td>
					</tr>
					<tr>
						<td>0</td>
						<td>제목제목제목제목제목</td>
						<td>내용내용내용내용내용내용내용</td>
						<td>2022-09-22</td>
						<td>0</td>
						<td>0</td>
					</tr>
					<tr>
						<td>0</td>
						<td>제목제목제목제목제목</td>
						<td>내용내용내용내용내용내용내용</td>
						<td>2022-09-22</td>
						<td>0</td>
						<td>0</td>
					</tr>
					<tr>
						<td>0</td>
						<td>제목제목제목제목제목</td>
						<td>내용내용내용내용내용내용내용</td>
						<td>2022-09-22</td>
						<td>0</td>
						<td>0</td>
					</tr>
					<tr>
						<td>0</td>
						<td>제목제목제목제목제목</td>
						<td>내용내용내용내용내용내용내용</td>
						<td>2022-09-22</td>
						<td>0</td>
						<td>0</td>
					</tr>
					<tr>
						<td>0</td>
						<td>제목제목제목제목제목</td>
						<td>내용내용내용내용내용내용내용</td>
						<td>2022-09-22</td>
						<td>0</td>
						<td>0</td>
					</tr>
					<tr>
						<td>0</td>
						<td>제목제목제목제목제목</td>
						<td>내용내용내용내용내용내용내용</td>
						<td>2022-09-22</td>
						<td>0</td>
						<td>0</td>
					</tr>
					<tr>
						<td>0</td>
						<td>제목제목제목제목제목</td>
						<td>내용내용내용내용내용내용내용</td>
						<td>2022-09-22</td>
						<td>0</td>
						<td>0</td>
					</tr>
					<tr>
						<td>0</td>
						<td>제목제목제목제목제목</td>
						<td>내용내용내용내용내용내용내용</td>
						<td>2022-09-22</td>
						<td>0</td>
						<td>0</td>
					</tr>
					<tr>
						<td>0</td>
						<td>제목제목제목제목제목</td>
						<td>내용내용내용내용내용내용내용</td>
						<td>2022-09-22</td>
						<td>0</td>
						<td>0</td>
					</tr>
					<tr>
						<td>0</td>
						<td>제목제목제목제목제목</td>
						<td>내용내용내용내용내용내용내용</td>
						<td>2022-09-22</td>
						<td>0</td>
						<td>0</td>
					</tr>
				</tbody>
			</table>
		</div>
		<br>
		<p>1 2 3 4 5</p>
	</div>
</body>
</html>